//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherProject.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherReportTable
    {
        public int WeatherReportId { get; set; }
        public string CityName { get; set; }
        public string WeatherName { get; set; }
        public Nullable<int> MaxTemperature { get; set; }
        public Nullable<int> MinTemperature { get; set; }
        public Nullable<int> RainRate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
